### ISSUE TITLE
在csk6002_9s_nano板子运行lisa term打开串口后无法写数据，reset也无响应

### ISSUE THREAD

**Issue by chengmeifang** [LISTENAI/lisa-plugin-term#1]
![image](https://user-images.githubusercontent.com/105494363/169488654-bef04305-6ea0-4b35-84e7-16fca31ea064.png)

**Comment by xingrz** [comment]
更新了支持拖拽的DAPLink固件？

**Comment by xingrz** [comment]
[stm32f103xb_csk6_nanokit_if_crc.bin.zip](https://github.com/LISTENAI/lisa-plugin-term/files/8738598/stm32f103xb_csk6_nanokit_if_crc.bin.zip)

是 Windows 的串口和串口烧录冲突了。先临时把 DAPLink 固件换成这个不带串口烧录的吧。

**Comment by xingrz** [comment]
关联 LISTENAI/cskburn#2，不属于 lisa term 的问题，先关了。

**Comment by xingrz** [comment]
已修复。需要更新 cskburn 和 DAPLink 固件。

* https://github.com/LISTENAI/cskburn/releases/tag/v1.15.0
* https://github.com/LISTENAI/DAPLink/releases/tag/nanokit-v0258-4
